### PR TITLE
Some minor changes to make local dev setup work

### PR DESCRIPTION
**Pull request by rvenkatesh25**
- 8u66+8u65arm java version is apparently not available, it fails to download. Upgraded the java version
- removed the .vagrant folder from source control since local installation will generate those files (if present, it crib about uid 1000 not available for e.g.)

### CODE REVIEW

**Comment by vmahedia** [comment]
Sorry about java update problem, that was already updated in the [roger-mesos](https://github.com/seomoz/roger-mesos). We should just have one repo.

**Comment by arunabha** [comment]
Thanks a lot Venky, this is awesome !

**Comment by ankanm** [comment]
Folks

I tried merging the latest from roger-mesos to ensemble. It's not trivial.

Given that roger-mesos is way ahead (including mesos/marathon/docker
versions + other changes across the repo) we could do 1 of the following -

Option 1 - Create PR against roger-mesos (and recreate ensemble as a fork
in mesosup and keep it updated.)
Option 2 - Create PR against a re-forked roger-mesos (name it ensemble as
is) under mesosup (and keep the fork link as this helps in keeping the repo
updated.)
Option 3 - Make the non-trivial merge to ensemble and continue to keep it
updated (this is a hassle actually)

We're currently on Option 3 which is a real pain to maintain.

Can we move to option 1 or 2?
- Ankan.

**Comment by rvenkatesh25** [comment]
Option 1 seems intuitive to understand, I vote for that.
Agree that current scheme (#3) is tedious

**Comment by rvenkatesh25** [comment]
BTW, would there be any complications if I (legally an employee of Yahoo) make pull requests and contribute to seomoz org?

**Comment by arunabha** [comment]
Yep, technically Moz has not released any IP claims to the project so if we
contribute to roger-mesos, we should not assume anything unless Moz adds an
indemnity clause.

How about we add stuff to ensemble and port changes back to roger-mesos ?

**Comment by ankanm** [comment]
IANAL but -
- There's an Apache 2.0 license in the code and it's public/open source.
  And in both options 1 & 2 we'll keep the mesosup repo updated.
- If there's a problem it is likely going to be at your employer's side for
  the work you do. You should check with them on what the general policy is
  for OS contribution.

In any case we could go with option 2 (Create PR against a re-forked
roger-mesos under mesosup). But keeping the fork link is needed else it's a
huge pain maintaining changes at both sides. For roger-mesos, the bulk of
the update (e.g. version upgrades etc) is going to happen in
seomoz/roger-mesos. And occasional changes on mesosup side. So, all we need
to do is always get the latest from seomoz before making any updates. Also,
if we do make updates at mesosup end, Vinit or I will merge the PR into
roger-mesos. With the github fork link in place all this is trivial.

For things that we completely develop under mesosup (like say junction - if
we ever get to that), we should just do that and seomoz could simply use
mesosup/junction like any other OS project (like mesos or marathon itself).

Does this make sense?

**Comment by ankanm** [comment]
I just forked seomoz/roger-mesos into mesosup -
https://github.com/mesosup/roger-mesos.

So, we can go with either of the options 1 or 2 are possible (but let's
just do one!)

**Comment by vmahedia** [comment]
Why not just have one repo? Nobody cares where you contribute stuff until you start making money off of it, significant amount that is. I believe forking and merging is technically the same thing as contributing directly, it's just a different method of doing exactly same thing.

@rvenkatesh25 you might need to talk to "the one who cannot be named and writes" I doubt you want to get involve in endless chain of emails eventually saying nothing of substance. @codingtwinky tried doing that, you might want to check with him.

**Comment by arunabha** [comment]
On Sun, Apr 10, 2016 at 12:27 PM, Vinit Mahedia notifications@github.com
wrote:

> Why not just have one repo? Nobody cares where you contribute stuff until
> you start making money off of it, significant amount that is. I believe
> forking and merging is technically the same thing as contributing directly,
> it's just a different method of doing exactly same thing.
> 
> Well, you really should read your employment contract sometime :-).

One big issue is that roger-mesos is owned by the seomoz org in github, and
I imagine that Moz would prefer roger-mesos to stay closely aligned with
Moz's needs. Even today, we effectively have half the team at mesosup
outside of Moz, and in the future this could skew even further. However the
practical reality is that Ankan and Vineet are the only people doing
significant development right now.

Let's discuss this over a quick hangout. Is everyone free tonight ?

**Comment by vmahedia** [comment]
I am free. It's just that I am really confused about which commit is on what repo and in future, it will create even more confusion when we have more commit.

**Comment by vmahedia** [comment]
For some reason, the java update failed for me, manual install worked. Might be something wrong at my end but putting it here if someone else runs into the same issue, there might be some problem.
`stderr: E: Version '8u77+8u77arm-1~webupd8~1' for 'oracle-java8-installer' was not found`

**Comment by ankanm** [comment]
I'm available tonight.

**Comment by arunabha** [comment]
Looks like Venky isn't free. Let's try to do this sometime this coming week.

**Comment by rvenkatesh25** [comment]
Sorry, I was out during the day. We can talk tonight. What time works for everyone?

**Comment by rvenkatesh25** [comment]
Or let's plan for tomorrow, Monday 8PM. 

Btw, I am leaving for India on 15th (friday) and I will be there until may 9th.

**Comment by arunabha** [comment]
Is everyone still around ? If so let's try to connect today. Reply back if
you see this and are ok for a chat at 8 pm PST

**Comment by rvenkatesh25** [comment]
I'm in

**Comment by arunabha** [comment]
Texting Vineet and Ankan.

**Comment by ankanm** [comment]
I'm in.

**Comment by arunabha** [comment]
https://plus.google.com/hangouts/_/grmwknyocrgzpaiitfz3irwnpme?authuser=0&hl=en

**Comment by rvenkatesh25** [comment]
Closing. Build against the forked roger-mesos repo now

**Pull request closed without merging**
